# no name specified - filename will be used instead.
name="sqlite"
command = "./sqlite -Xms1g -Xmx1g"
working-directory = "/home/Opensource/practice-project/sqlite/build/native/nativeCompile"
stdout = "./logs/stdout.log"
stdout-rotate-size = "100 MB"
stdout-should-append-timestamp-to-filename = false

[restart]
strategy = "always"
